feat(project): project
Nicanor008/shoman-api pull request #14
Opened 2021-01-14 15:10 UTC by Georgeygigz

- implementation to update project
- implementation to delete project
- implement soft delete

2021-01-15 06:28 UTC, kwameAsiago approved these changes

2021-01-15 07:26 UTC, Ruiru11 approved these changes
This looks good but its advisable to do a mongo soft delete maybe using `mongoose_delete` that creates fields on the object model in the db directly without you having to find and update. But this is good stuff

2021-01-15 08:52 UTC, neymarjimoh reviewed
this is nice. there should also be room for deleting projects from the database permanently

2021-01-15 09:03 UTC, Nicanor008 commented
> This looks good but its advisable to do a mongo soft delete maybe using `mongoose_delete` that creates fields on the object model in the db directly without you having to find and update. But this is good stuff

good idea, I didn't know there's a tool to handle that. I've created this issue [here](https://github.com/Nicanor008/shoman-api/issues/15). But not urgently needed on MVP release

2021-01-15 09:06 UTC, Nicanor008 commented
> this is nice. there should also be room for deleting projects from the database permanently

yes, I agree with you @neymarjimoh, however, for MVP release we will require all projects. if deleted, Shoman admin is granted access and the admin can decide what to do with the project on update. Permanent deletion can only be done by admin

2021-01-15 09:14 UTC, Nicanor008 requested changes

2021-01-15 09:14 UTC, Nicanor008 commented on src/api/v1/project/project_controllers.js
> +    Project.findOneAndUpdate(query, { isDeleted: true })
grant showman access after deleting, `showmanAccess: true`
```suggestion
    Project.findOneAndUpdate(query, { isDeleted: true, showmanAccess: true })
```

2021-01-18 14:32 UTC, neymarjimoh commented
> > this is nice. there should also be room for deleting projects from the database permanently
> 
> yes, I agree with you @neymarjimoh, however, for MVP release we will require all projects. if deleted, Shoman admin is granted access and the admin can decide what to do with the project on update. Permanent deletion can only be done by admin

Alright @Nicanor008

2021-01-21 05:38 UTC, Nicanor008 approved these changes

2021-01-21 05:38 UTC, merged