Content crud
Nicanor008/shoman-api pull request #17
Opened 2021-01-24 04:10 UTC by neymarjimoh

- handles CRUD on learning content

2021-01-25 09:28 UTC, Nicanor008 commented
@neymarjimoh could you kindly share a screenshot of your postman POST.

2021-01-25 10:07 UTC, Nicanor008 requested changes
The update doesn't seem to work, response is 200 but nothing has been updated. Not sure of delete, just gives `Auth Failed`, but will retry. Progress is good @neymarjimoh, good job. Just fix the minor issues.

2021-01-25 10:07 UTC, Nicanor008 commented on src/api/v1/contents/content_controllers.js
> +        const isdateValid = validateDate(dueDate)
`dueDate` is not defined, shouldn't it be deadline?

2021-01-25 15:56 UTC, neymarjimoh commented on src/api/v1/contents/content_model.js
> +        category: stringRequired,
okay

2021-01-25 15:57 UTC, neymarjimoh commented on src/api/v1/contents/content_controllers.js
> +        const isdateValid = validateDate(dueDate)
yeah,

2021-01-26 09:16 UTC, neymarjimoh commented
> The update doesn't seem to work, response is 200 but nothing has been updated. Not sure of delete, just gives `Auth Failed`, but will retry. Progress is good @neymarjimoh, good job. Just fix the minor issues.

can i see a screnshot @Nicanor008

2021-01-26 09:42 UTC, Nicanor008 commented
> > The update doesn't seem to work, response is 200 but nothing has been updated. Not sure of delete, just gives `Auth Failed`, but will retry. Progress is good @neymarjimoh, good job. Just fix the minor issues.
> 
> can I see a screenshot @Nicanor008
@neymarjimoh This is Patch for a mentor user, gives 200 but doesn't update. 
<img width="1260" alt="Screenshot 2021-01-26 at 12 41 38" src="https://user-images.githubusercontent.com/25298492/105828146-dd45a800-5fd3-11eb-992b-b18ef6d131f3.png">

2021-01-26 10:00 UTC, neymarjimoh commented
> > > The update doesn't seem to work, response is 200 but nothing has been updated. Not sure of delete, just gives `Auth Failed`, but will retry. Progress is good @neymarjimoh, good job. Just fix the minor issues.
> > 
> > 
> > can I see a screenshot @Nicanor008
> 
> @neymarjimoh This is Patch for a mentor user, gives 200 but doesn't update.
> <img alt="Screenshot 2021-01-26 at 12 41 38" width="1260" src="https://user-images.githubusercontent.com/25298492/105828146-dd45a800-5fd3-11eb-992b-b18ef6d131f3.png">

alright, please can you make a get request to see if its updated?

2021-01-27 03:40 UTC, Nicanor008 requested changes

2021-01-27 03:40 UTC, Nicanor008 commented on src/api/v1/contents/content_controllers.js
> +        return responseHandler(res, 200, updatedContent, 'Task updated successfully')
you only updating the deadline? you've defined `updatedFields` as an empty object but you not initializing with anything. The update should allow the author to update anything on the learning content they created. Kindly check up this function @neymarjimoh

2021-01-28 01:13 UTC, neymarjimoh commented on src/api/v1/contents/content_controllers.js
> +        return responseHandler(res, 200, updatedContent, 'Task updated successfully')
yeah, noticed it 
a simple spread on the `req.body` object would have been used to initialize the `updatedFields`

2021-02-01 07:52 UTC, Nicanor008 approved these changes

2021-02-01 07:52 UTC, Nicanor008 commented on src/api/v1/contents/index.js
> +router.delete('/contents/:contentId',isAdmin, deleteContent)
We should use soft delete for the creator(mento/admin) and hard delete for admin. For now, I'll merge this, but can be worked on later.

2021-02-01 07:53 UTC, merged