added mentee to apply for mentorship
Nicanor008/shoman-api pull request #2
Opened 2020-11-27 15:49 UTC by neymarjimoh

- mentees can apply for mentorship and choose a track
- requires track/stack to be available

2020-11-27 16:06 UTC, Nicanor008 commented on package.json
> +    "express-validator": "^6.7.0",
Why we using two validators express-validator and validator?

2020-11-27 16:07 UTC, Nicanor008 commented on src/controllers/mentee.js
> +        next(new InternalServerError(error))
Good error catching

2020-11-27 16:11 UTC, Nicanor008 requested changes

2020-11-27 16:11 UTC, Nicanor008 commented on src/middlewares/validation.js
> +export const validationMW = (req, res, next) => {
what does MW stands for, any better way to write this functionName?

2020-11-27 16:11 UTC, Nicanor008 commented on src/routes/mentees/auth.js
> +router.get('/ddd', (req, res) => {
naming?? ddd???

2020-11-27 16:11 UTC, Nicanor008 commented on src/utils/customError.js
> +    constructor(statusCode, message, errors) {
Awesome

2020-11-27 16:26 UTC, neymarjimoh commented on package.json
> +    "express-validator": "^6.7.0",
I used it cos express-validator and joi worked well and are easy to implement in express applications

2020-11-27 16:28 UTC, neymarjimoh commented on src/middlewares/validation.js
> +export const validationMW = (req, res, next) => {
Ok.. would change it..
Couldn't think of a better name, it stands for middle ware to return validation error responses or next chain of request

2020-11-27 16:29 UTC, neymarjimoh commented on src/routes/mentees/auth.js
> +router.get('/ddd', (req, res) => {
Totally forgot to remove this.. it was the first endpoint I created to test if the mentees routes were working

2020-11-27 16:29 UTC, neymarjimoh commented on src/utils/customError.js
> +    constructor(statusCode, message, errors) {
Thanks

2020-11-28 10:30 UTC, Nicanor008 requested changes

2020-11-28 10:30 UTC, Nicanor008 commented on src/index.js
> +app.use(mentees);
This is different from the other(line 52, 53). Could we stick to one style then maybe refactor later.

2020-11-28 10:30 UTC, Nicanor008 commented on src/index.js
> +import mentees from "./routes/mentees";
Move the mentees folder inside the endpoints/api.
```suggestion
import mentees from "./routes/api/mentees";
```

2020-11-28 10:30 UTC, Nicanor008 commented on src/models/track.js
> +                type: Schema.Types.ObjectId,
I don't understand `track.js`. Is it list learning tracks available?

2020-11-28 17:46 UTC, neymarjimoh commented on src/index.js
> +app.use(mentees);
Okay n

2020-11-30 15:29 UTC, Nicanor008 commented
Kindly adopt the new folder structure, and you can also use the /tracks endpoints to retrieve all tracks and add to the application_schema. Note that, this feature is required by tomorrow, Tuesday.

2020-11-30 19:37 UTC, neymarjimoh commented
> Kindly adopt the new folder structure, and you can also use the /tracks endpoints to retrieve all tracks and add to the application_schema. Note that, this feature is required by tomorrow, Tuesday.

alright would do so

2020-12-02 03:36 UTC, Nicanor008 approved these changes

2020-12-02 03:36 UTC, merged