Fix email services: setup OAuth2 on the shoman email address
Nicanor008/shoman-api pull request #4
Opened 2020-11-29 17:13 UTC by Ruiru11

### What does this PR do
- switch email services to OAuth2 

#### Description of Task to be completed?
- Allow users to receive email on registration
- Allow user to request for a password reset(email is sent)
- Allow user to reset the password using the link sent
- Allow user to get a notification on successful change 

#### How to test this pull request
* clone the project
* checkout to `ch-move-email-to-auth`
* run  `npm install``
* Request for .env credentials from admin
* use `npm run dev` to fire up the server
* use postman to test the user api's

#### relevant links to this story 
###### NONE

2020-11-30 15:15 UTC, Nicanor008 commented
For some reason, it still shows that error
<img width="452" alt="Screenshot 2020-11-30 at 18 12 57" src="https://user-images.githubusercontent.com/25298492/100627350-f3b6e680-3337-11eb-8ae9-faa01e957a5d.png">

2020-11-30 20:55 UTC, Ruiru11 commented
> For some reason, it still shows that error
> <img alt="Screenshot 2020-11-30 at 18 12 57" width="452" src="https://user-images.githubusercontent.com/25298492/100627350-f3b6e680-3337-11eb-8ae9-faa01e957a5d.png">

use the latest .env file if you still find the issue we can have a meeting to resolve it

2020-12-01 08:03 UTC, Nyakaru reviewed
@Ruiru11 @Nicanor008 If it is okay with you, I can pull this branch and make some improvements.

2020-12-01 08:03 UTC, Nyakaru commented on src/googleservices/email.js
> +export const sendMail = async (data) => {
@Ruiru11 I have an idea. Why can't we just create a reusable transporter that we can use everywhere? As opposed to initializing in every file?

2020-12-01 08:03 UTC, Nyakaru commented on src/googleservices/email.js
> +        html: `<div><h4>Thank you ${data.Username} and welcome to the Shoman Mentorship Progmram where we help you levelup  your Skills</h4></div>
Then here instead of writing Html directly, we can use e-js templates. There are more neat

2020-12-01 17:10 UTC, Ruiru11 commented on src/googleservices/email.js
> +export const sendMail = async (data) => {
Yeah sure brother  that would be  anice way to approach it so that in future if we have  other events that need email action we can just  the transporter .. good stuff

2020-12-01 17:11 UTC, Ruiru11 commented on src/googleservices/email.js
> +        html: `<div><h4>Thank you ${data.Username} and welcome to the Shoman Mentorship Progmram where we help you levelup  your Skills</h4></div>
You will handle that as you create the reusable  transporter?

2020-12-01 18:15 UTC, Nyakaru commented on src/googleservices/email.js
> +        html: `<div><h4>Thank you ${data.Username} and welcome to the Shoman Mentorship Progmram where we help you levelup  your Skills</h4></div>
Yes I will. I'm waiting for @Nicanor008 to send me the .env or do you have the latest .env?

2020-12-02 08:01 UTC, Nyakaru commented
@Ruiru11 @Nicanor008 @neymarjimoh Please review this PR. It has a lot of changes

2020-12-02 12:19 UTC, Ruiru11 commented
> @Ruiru11 @Nicanor008 @neymarjimoh Please review this PR. It has a lot of changes

i am testing out and its not sending email and no error. On your end does it send ?

2020-12-02 14:57 UTC, Nicanor008 commented
Awesome implementation @Nyakaru, plus docker 😉. 

Maybe you could also move any functionality in routes to api/v1/auth

However, am facing `no refresh token set` on running `npm run dev`
<img width="634" alt="Screenshot 2020-12-02 at 17 54 36" src="https://user-images.githubusercontent.com/25298492/100889074-cdc04c00-34c7-11eb-997c-902a33201f34.png">

2020-12-02 16:43 UTC, Nyakaru commented
> Awesome implementation @Nyakaru, plus docker 😉.
> 
> Maybe you could also move any functionality in routes to api/v1/auth
> 
> However, am facing `no refresh token set` on running `npm run dev`
> <img alt="Screenshot 2020-12-02 at 17 54 36" width="634" src="https://user-images.githubusercontent.com/25298492/100889074-cdc04c00-34c7-11eb-997c-902a33201f34.png">

This is sometimes a problem with environment variables when they are not read correctly. You can try source afresh or remove the export part in your .env. When you say "any functionality" I believe you mean routes, models, and controllers, right? The utils and the rest to just sit where they are currently?

2020-12-02 16:47 UTC, neymarjimoh commented on docker-compose.yml
> +      - '27018:27017'
testing this; the data would not persist after stopping the containers, i think you should use volumes to persist the mongodb data so on starting and stopping the containers, they still persist

2020-12-03 05:05 UTC, Nicanor008 requested changes

2020-12-03 05:05 UTC, Nicanor008 commented on src/utils/email.js
> +
Add here to solve the error i'm facing
```suggestion
require('dotenv').config()
```

2020-12-03 20:23 UTC, Nyakaru commented on src/utils/email.js
> +
Okay I will

2020-12-03 20:24 UTC, Nyakaru commented on docker-compose.yml
> +      - '27018:27017'
I will organise a call to explain this to you

2020-12-03 21:10 UTC, neymarjimoh commented on docker-compose.yml
> +      - '27018:27017'
Okay

2020-12-04 14:21 UTC, Nyakaru commented
@Nicanor008 @Ruiru11 the PR is ready please see it through to develop/main

2020-12-04 14:52 UTC, Nicanor008 approved these changes

2020-12-04 14:52 UTC, merged