working on CRUD Team api
Nicanor008/shoman-api pull request #9
Opened 2020-12-11 15:44 UTC by neymarjimoh

crud Team api:
- creation of team
- viewing all teams
- viewing a team
- deleting a team
- assigning mentees to a team

2020-12-13 06:48 UTC, Nicanor008 requested changes

2020-12-13 06:48 UTC, Nicanor008 commented on src/api/v1/teams/team_controllers.js
> +const User = require('../users/users_model')
Stick to es6 imports

2020-12-13 06:48 UTC, Nicanor008 commented on src/api/v1/teams/team_controllers.js
> +        const { menteesId } = req.body
We also mentor to a team, so include mentorId

2020-12-13 06:53 UTC, Nicanor008 requested changes

2020-12-13 06:53 UTC, Nicanor008 commented on src/api/v1/teams/index.js
> +router.post('/teams/new', validations.teamCreateRules(), validate, createTeam)
Let's stick to one endpoint for POST and GET methods
```suggestion
router.post('/teams', validations.teamCreateRules(), validate, createTeam)
```

2020-12-13 07:01 UTC, Nicanor008 commented on src/api/v1/teams/team_controllers.js
> +            teamNumber = 'SH-101' // starting with 101 but could be changed
Maybe name it in full
```suggestion
            teamNumber = 'SHOMAN-101' // starting with 101 but could be changed
```

2020-12-13 07:09 UTC, Nicanor008 commented on src/api/v1/teams/team_controllers.js
> +        const { team_name, mentorId, trackId } = req.body
You can also add menteeId, but it's optional on the POST method. So a user creating a team can decide to add a mentee on POST or on the PUT request.

Also on the PUT request you can add mentorId in the `req.body`, will also be optional. I know a team is supposed to be updated by a mentor or an admin, but will be awesome to update a mentor

2020-12-13 07:22 UTC, Nicanor008 requested changes

2020-12-13 07:22 UTC, Nicanor008 commented on src/api/v1/teams/index.js
> +import { isAdmin, isAuthenticated } from '../../../middlewares/auth'
is this still used in this file?

2020-12-13 07:22 UTC, Nicanor008 commented on src/api/v1/teams/index.js
> +router.put('/teams/add-user/:teamId', validateTeamId, validations.addMenteesToTeamRules(), validate, addUsersToTeam)
I would prefer to use the `.patch` method here since it's an existing resource.
https://stackoverflow.com/questions/24241893/should-i-use-patch-or-put-in-my-rest-api#24241955

2020-12-13 14:41 UTC, Nicanor008 requested changes

2020-12-13 17:12 UTC, neymarjimoh commented on src/api/v1/teams/team_controllers.js
> +const User = require('../users/users_model')
I did  this cause User model was exported in CommonJS

2020-12-16 05:16 UTC, Nicanor008 requested changes
Good work on feedback implementation, check on the feedback

2020-12-16 05:16 UTC, Nicanor008 commented on src/api/v1/teams/index.js
> +router.post('/teams', validations.teamCreateRules(), validate, createTeam)
Protect to only admins and mentors

2020-12-16 05:16 UTC, Nicanor008 commented on src/api/v1/teams/team_controllers.js
> +        }
Take a look on this again, it gives me `SHOMAN-NAN`

2020-12-16 05:16 UTC, Nicanor008 commented on src/api/v1/teams/team_controllers.js
> +        teams = await Team.find(queryOptions)
you can also use mongo aggregate function to get users(mentor, and mentee) details.That's if you can make it, not so important at the moment though.

2020-12-16 06:17 UTC, Nyakaru commented on src/api/v1/teams/team_controllers.js
> +        next(new InternalServerError(error))
@neymarjimoh I do not know how this implementation works but I am just wondering why not return a response with an error rather than passing it to next?

2020-12-16 08:18 UTC, neymarjimoh commented on src/api/v1/teams/index.js
> +router.post('/teams', validations.teamCreateRules(), validate, createTeam)
The middlewares aren't working as expected. Try protecting any other route. It always returns errors that I don't understand

2020-12-16 08:18 UTC, neymarjimoh commented on src/api/v1/teams/team_controllers.js
> +        }
I tested this severally.. and it's working fine my side.
Did you pull?

2020-12-16 08:19 UTC, neymarjimoh commented on src/api/v1/teams/team_controllers.js
> +        teams = await Team.find(queryOptions)
Okay.

2020-12-16 08:22 UTC, neymarjimoh commented on src/api/v1/teams/team_controllers.js
> +        next(new InternalServerError(error))
I'm trying not to be repeating  codes (unknown server error as an example) rather just create an error handler that could catch the errors and return the response cause all controllers would return this.

2020-12-16 08:24 UTC, neymarjimoh commented on src/api/v1/teams/team_controllers.js
> +        next(new InternalServerError(error))
Returning same error response in every controller is not a DRY process

2020-12-16 15:27 UTC, Nicanor008 commented on src/api/v1/teams/index.js
> +router.post('/teams', validations.teamCreateRules(), validate, createTeam)
ooohhh haven't checked, will check it out. For now then we can leave it as is

2020-12-16 15:27 UTC, Nicanor008 commented on src/api/v1/teams/team_controllers.js
> +        }
I did, will recheck

2020-12-16 15:32 UTC, Nicanor008 commented on src/api/v1/teams/index.js
> +router.post('/teams', validations.teamCreateRules(), validate, createTeam)
@Nyakaru you can check up and share status

2020-12-17 11:16 UTC, Nyakaru commented on src/api/v1/teams/index.js
> +router.post('/teams', validations.teamCreateRules(), validate, createTeam)
Hey @neymarjimoh what is the error? I can help you debug it

2020-12-17 13:18 UTC, neymarjimoh commented on src/api/v1/teams/index.js
> +router.post('/teams', validations.teamCreateRules(), validate, createTeam)
Alright.. I'll send you a screenshot via slack.

2021-01-10 10:54 UTC, Nicanor008 approved these changes

2021-01-10 10:54 UTC, merged